### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by uncenter** [uncenter/learn-eleventy#3]
- [ ] Lessons 18-21: Remove Gulp + asset pipeline in favor of processing within Eleventy, i.e. Sass as a template language and `11ty/eleventy-img` - #1.
- [ ] [Lesson 5](https://learn-eleventy.pages.dev/lesson/5): Consider switching to `11ty/eleventy-img` instead of passthrough copy?
- [ ] All: Remove references of 'modules' and 'sections'; I don't think the lessons were ever divided into those (e.g. [Lesson 16](https://learn-eleventy.pages.dev/lesson/16)).
- [ ] Create folder for each lesson's completed files - #2.

**Comment by SteelMaverick** [comment]
Hey there, I'm just wondering, was Lesson 11's pagination problematic to begin with? I mulled over this myself but I think the original implementation of it is fine especially when you compare it to the finished site. I did do a "fix" for it swapping the labels but it just doesn't look right when you compare the end result contextually:

**Current**

<pre>href.prev, <b>PrevText:newer/prev</b>, backwards <- 0, 1, 2 -> href.next, <b>NextText:older/next</b>, forwards</pre>

**Edited**

<pre>href.prev, <b>NextText:newer/next</b>, backwards <- 0, 1, 2 -> href.next, <b>PrevText:older/prev</b>, forwards</pre>

Pretty much, I think the current implementation is correct with the `PrevText` labelling the `href.prev` link while `NextText` is for labelling the `href.next` link.

Thoughts?

**Comment by rakibyt01912-dev** [comment]
Hey there, I'm just wondering, was Lesson 11's pagination problematic to begin with? I mulled over this myself but I think the original implementation of it is fine especially when you compare it to the finished site. I did do a "fix" for it swapping the labels but it just doesn't look right when you compare the end result contextually:

Current

href.prev, PrevText:newer/prev, backwards <- 0, 1, 2 -> href.next, NextText:

href.prev, NextText:newer/next, backwards <- 0, 1, 2 -> href.next, PrevText:older/prev, forwards
Pretty much, I think the current implementation is correct with the PrevText labelling the href.prev link while NextText is for labelling the href.next link.
